# Generated by Django 4.0.6 on 2022-07-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_back_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tags', models.CharField(max_length=32, null=True)),
                ('flashcards', models.ManyToManyField(to='flashcards.flashcard')),
                ('language_to_learn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_list_lang', to='flashcards.language')),
                ('learning_in_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_list_lang', to='flashcards.language')),
            ],
        ),
    ]
