# Generated by Django 4.0.6 on 2022-07-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='flashcards',
            field=models.ManyToManyField(null=True, to='flashcards.flashcard'),
        ),
    ]
