# Generated by Django 4.0.6 on 2022-07-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_list_flashcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='flashcards',
            field=models.ManyToManyField(blank=True, to='flashcards.flashcard'),
        ),
    ]
