# Generated by Django 4.0.6 on 2022-08-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_list_flashcards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='flashcards',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='list',
            field=models.ManyToManyField(null=True, to='flashcards.list'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], default=1, null=True)),
                ('language_to_learn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_course_lang', to='flashcards.language')),
                ('learning_in_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_course_lang', to='flashcards.language')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='course',
            field=models.ManyToManyField(null=True, to='flashcards.course'),
        ),
    ]
