# Generated by Django 4.0.6 on 2022-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_remove_list_flashcards_flashcard_list_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='list',
            field=models.ManyToManyField(blank=True, to='flashcards.list'),
        ),
        migrations.AlterField(
            model_name='list',
            name='course',
            field=models.ManyToManyField(blank=True, to='flashcards.course'),
        ),
    ]
