# Generated by Django 4.0.6 on 2022-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_alter_flashcard_list_alter_list_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='list',
            new_name='lists',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='course',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
