# Generated by Django 4.0.6 on 2022-08-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_rename_list_flashcard_lists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='showed',
            field=models.CharField(default='<django.db.models.fields.CharField> - <django.db.models.fields.CharField>', max_length=190),
        ),
    ]
