# Generated by Django 4.0.6 on 2022-08-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_remove_flashcard_showed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Upper Intermediate'), (5, 'Advanced'), (6, 'Proficient')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='mastery_level',
            field=models.IntegerField(choices=[(1, 'Hard'), (2, 'Good'), (3, 'Easy'), (4, 'Excellent')], default=1),
        ),
    ]
