# Generated by Django 4.0.6 on 2022-08-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_remove_list_courses_list_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='courses',
        ),
        migrations.AddField(
            model_name='list',
            name='courses',
            field=models.ManyToManyField(blank=True, to='flashcards.course'),
        ),
    ]
