# Generated by Django 4.0.6 on 2022-08-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_remove_list_courses_list_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='courses',
        ),
        migrations.AddField(
            model_name='list',
            name='courses',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='flashcards.course'),
            preserve_default=False,
        ),
    ]
