# Generated by Django 4.0.6 on 2022-08-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0018_flashcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
