# Generated by Django 4.0.6 on 2022-08-09 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0019_alter_flashcard_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, to='flashcards.course')),
                ('flashcards', models.ManyToManyField(blank=True, to='flashcards.flashcard')),
                ('languages_to_learn', models.ManyToManyField(blank=True, related_name='user_learn_langs', to='flashcards.language')),
                ('learning_in_languages', models.ManyToManyField(blank=True, related_name='user_langs', to='flashcards.language')),
                ('lists', models.ManyToManyField(blank=True, to='flashcards.list')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
